### PR TITLE
Inherited value can't be removed #811

### LINKED ISSUE #811: Inherited value isn't saving
**Describe the bug**
When you edit a flight after you write a value this is saved, but if you left field in blank to set the value in inherited the value isn't saved and return to previous value.

**Version**
7.0.0-dev+200903.51004b

**To Reproduce**
https://i.imgur.com/ynmXus3.gif

**Expected behavior**
delete the value to set inherited and save it.

### PR DESCRIPTION
**Pull request by nabeelio**
Closes #811

### CODE REVIEW

File: app/Services/FareService.php [hunk 1]
```diff
@@ -106,14 +108,8 @@ public function setForFlight(Flight $flight, Fare $fare, array $override = []):
     {
         $flight->fares()->syncWithoutDetaching([$fare->id]);
 
-        foreach ($override as $key => $item) {
-            if (!$item) {
-                unset($override[$key]);
-            }
-        }
```
Comment (nabeelio) [inline app/Services/FareService.php:113]: Main fix here, don't filter out null'd values
