### PR TITLE
Aircraft's FIN should be unique

### LINKED ISSUE #2014: Duplicate FIN number throws a 500 error
**Describe the bug**
When adding a new aircraft to a subfleet if you add a FIN number that is already in use instead of getting a warning you get a 500 error

**Version**
7.0.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  subfleet, manage aircraft, add new aircraft
2. Add a FIN number that you have already used
3. Press save
4. See error 500

**Expected behaviour**
I would expect a warning that it was in use like the registration does

### PR DESCRIPTION
**Pull request by arthurpar06**
Closes #2014 

Should be applied to both `v7` and `v8`

### CODE REVIEW

File: app/Models/Aircraft.php [hunk 1]
```diff
@@ -105,7 +105,7 @@ class Aircraft extends Model
     public static $rules = [
         'name'          => 'required',
         'registration'  => 'required',
-        'fin'           => 'nullable',
+        'fin'           => 'nullable|unique:aircraft',
```
Comment (FatihKoz) [inline app/Models/Aircraft.php:108]: Just a question, does `|unique:airline` work ? I mean with a logic like fin is unique within the airline as we have an belongs to airline relationship, or maybe `|unique:subfleet` again based on a relationship ?

The main question is can we make something unique depending on the related model (like airline or subfleet) it belongs to ?

Comment (arthurpar06) [reply app/Models/Aircraft.php:108]: https://laravel.com/docs/12.x/validation#rule-unique

From my understanding, no. I believe this means that the FIN number should be unique in the `fin` column of the aircraft table (since I didn't specify a different column). I think if I use `unique:subfleet`, it will ensure that the FIN is unique within the subfleets table
