### PR TITLE
Make sure airline IDs are added to the expense

### LINKED ISSUE #1723: Subfleet and Aircraft Expenses Being Applied to Wrong Airline
Subfleet and Aircraft based expenses are being applied to all airlines, even to airlines without subfleets/aircraft.

**Version**
7.0.0-dev+231215.655f15

**To Reproduce**
1. Go to Admin > Fleets, pick one subfleet and click edit
2. Add some daily expenses to the subfleet
3. Either wait for daily cron to run at midnight or force run it
4. Check your cron log, you will see that the expense is applied to other airlines and subfleets too (!)
5. Also check your finances, or better transactions, you will see that the expense is applied at all assets (!)

**Expected behavior**
Daily / Monthly expenses should be applied to *relevant* subfleets / aircraft, not to all.

**Additional context**
Looks like there are logical problems while picking up proper objects.

image

image

image

```
[2023-12-16 16:02:49] production.INFO: Nightly: Applying daily expenses  
[2023-12-16 16:02:49] production.INFO: Charging to DSH  
[2023-12-16 16:02:49] production.INFO: Charging to DSC  
[2023-12-16 16:02:49] production.INFO: Charging to DSH  
[2023-12-16 16:02:49] production.INFO: Expense memo: "Subfleet Expense: Daily Check"; group: "Subfleet: Daily Check" charged!  
[2023-12-16 16:02:49] production.INFO: Charging to DSC  
[2023-12-16 16:02:49] production.INFO: Expense memo: "Subfleet Expense: Daily Check"; group: "Subfleet: Daily Check" charged!  
[2023-12-16 16:02:49] production.INFO: Nightly: Recalculating balances  
```
```
[2023-12-16 16:02:59] production.INFO: Monthly: Applying monthly expenses  
[2023-12-16 16:02:59] production.INFO: Charging to DSH  
[2023-12-16 16:02:59] production.INFO: Charging to DSC  
[2023-12-16 16:02:59] production.INFO: Charging to DSH  
[2023-12-16 16:02:59] production.INFO: Expense memo: "Subfleet Expense: Leasing Payments"; group: "Subfleet: Leasing Payments" charged!  
[2023-12-16 16:02:59] production.INFO: Charging to DSC  
[2023-12-16 16:02:59] production.INFO: Expense memo: "Subfleet Expense: Leasing Payments"; group: "Subfleet: Leasing Payments" charged!  
[2023-12-16 16:02:59] production.INFO: Charging to DSH  
[2023-12-16 16:02:59] production.INFO: Expense memo: "Aircraft Expense: Aircraft Leasing Expenses (TC-DSP)"; group: "Aircraft: Aircraft Leasing Expenses (TC-DSP-TC-DSP)" charged!  
[2023-12-16 16:02:59] production.INFO: Charging to DSC  
[2023-12-16 16:02:59] production.INFO: Expense memo: "Aircraft Expense: Aircraft Leasing Expenses (TC-DSP)"; group: "Aircraft: Aircraft Leasing Expenses (TC-DSP-TC-DSP)" charged!  
```

image

### PR DESCRIPTION
**Pull request by nabeelio**
Closes #1723

### CODE REVIEW

File: app/Http/Controllers/Admin/AircraftController.php [hunk 1]
```diff
@@ -327,10 +322,11 @@ public function expenses(int $id, Request $request): View
...
 
         if ($request->isMethod('post')) {
-            $expense = new Expense($request->post());
-            $expense->ref_model = Aircraft::class;
-            $expense->ref_model_id = $aircraft->id;
-            $expense->save();
+            $this->financeSvc->addExpense(
+                $request->post(),
+                $aircraft,
+                $aircraft->subfleet->airline_id
```
Comment (FatihKoz) [inline app/Http/Controllers/Admin/AircraftController.php:328]: `$aircraft->airline->id` is also possible.

https://github.com/nabeelio/phpvms/blob/ca565fc563d75c673f76207913473c080bceadf0/app/Models/Aircraft.php#L172

File: app/Database/migrations_data/2023_12_19_174436_correct_expenses.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+            $klass = end($ref);
+            $obj = $expense->getReferencedObject();
+        }
+
+        if (empty($obj)) {
+            return;
+        }
+
+        if ($klass === 'Airport') {
+            // TODO: Get an airline ID?
```
[the remark this answers is not in the document]
Comment (arthurpar06) [reply app/Database/migrations_data/2023_12_19_174436_correct_expenses.php:40]: Yes, I thought about it, but I don't believe we can define this type of expense in the frontend.

File: app/Services/Finance/RecurringFinanceService.php [hunk 3]
```diff
@@ -131,6 +140,8 @@ public function processExpenses($type = ExpenseType::DAILY): void
                     continue;
                 }
 
+                // Determine if this object actually belongs to this airline or not
+
```
[the remark this answers is not in the document]
Comment (nabeelio) [reply app/Services/Finance/RecurringFinanceService.php:144]: Thank you!

File: app/Services/FinanceService.php [hunk 4]
```diff
@@ -19,6 +21,40 @@ public function __construct(
...
+     * airline this needs to be charged to
+     *
+     * @param array      $attrs      Array of attributes
+     * @param Model|null $model      The model this expense is tied to
+     * @param int|null   $airline_id The airline this expense should get charged to
+     *
+     * @return Expense
+     */
+    public function addExpense(array $attrs, Model $model = null, int $airline_id = null): Expense
+    {
```
Comment (arthurpar06) [inline app/Services/FinanceService.php:35]: Maybe you should validate `$attrs` here, considering that when you call this function, you pass `$request->post()` or `$request->all()`, and it's not always a good idea to trust what the user may have entered and put it directly into the database.

**Review by arthurpar06 — CHANGES_REQUESTED** [review]

File: app/Services/FinanceService.php (hunk 4 above)
Comment (nabeelio) [reply app/Services/FinanceService.php:35]: The model rules should validate it but let me double check that

Comment (nabeelio) [reply app/Services/FinanceService.php:35]: Oh cool, looks like the auto style fixes worked

Comment (arthurpar06) [reply app/Services/FinanceService.php:35]: Yes, actually, it works only on branches of your repository, not on the PRs, I think. It works for my PRs because I also added it to my fork, and for your PRs because they are branches of your own repository.

**Comment by arthurpar06** [comment]
The workflow just failed due to Docker rate limiting; you just need to restart it for everything to go through, I think.

**Comment by nabeelio** [comment]
Ouch
